from ecc.qfs import qf_isogs,qf_isog_cycle,qf_isog_cycle_power,qf_sibs,cycs_from_ancestors,class_group_id
from ecc.nt import discfac,quad_rec,divisors
from ecc.identities import *

###########################
# Obtaining generating ls #
###########################

# This is start of bijection algorithm #
def generate_qfs_from_ls(qf0,lset):
    qfs = [qf0]
    for l in lset:
        qfls = []
        for qf in qfs:
            qfls+=qf_isog_cycle(qf,l)
        qfs = qfls
    return qfs

def generate_qfs_from_lks(qf0,lkset):
    qfs = [qf0]
    for lk in lkset:
        qfls = []
        for qf in qfs:
            qfls+=qf_isog_cycle_power(qf,lk)
        qfs = qfls
    return qfs


def qf_cyc_data(d,lcands):
    d0, c = discfac(d)
    qf0 = class_group_id(d)
    lcands = [l for l in lcands if c % l !=0 and quad_rec(d0,l)>=0]
    cycdata = {}
    gens = []
    for l in lcands:
        cycl = qf_isog_cycle(qf0,l)
        if len(cycl)>1 and cycl[1] not in gens and cycl[-1] not in gens:
            cycdata[l] = len(cycl)
            gens.append(cycl[1])
    return cycdata


def qf_cyc_data_ext(d,lcands):
    cycdata = qf_cyc_data(d,lcands)
    ls = [l for l in cycdata]
    for l in ls:
        for k in divisors(cycdata[l])[:-1]:
            cycdata[(l,k)] = cycdata[l]//k
    anc_data= cycs_from_ancestors(class_group_id(d))
    for l in anc_data:
        cycdata[(l,-1)]=len(anc_data[l])
    return {l:cycdata[l] for l in cycdata if type(l)==tuple}

def needs_orientation(d,cycdata):
    cld = clgr_size_gen(d)
    cld2 = clgr2_size(d)
    if cld % cld2 != 0:
        raise ValueError('Check size functions')
    for lk in cycdata:
        # Check if the class group mod the subgroup generated by lk is a 2 group
        if cld2 % (cld//cycdata[lk]) == 0:
            return False
    return True

def qf_lk_chains(d,lks):
    qf0 = class_group_id(d)
    lks2 =[]
    lks3pl = []
    for lk in lks:
        nlk = len(qf_isog_cycle_power(qf0,lk))
        if nlk == 2:
            lks2.append(lk)
        elif nlk > 2:
            lks3pl.append(lk)
    chains =[[qf0]]+[qf_isog_cycle_power(qf0,lk)[1:] for lk in lks2]
    if len(lks3pl) <2:
        return chains
    for lk in lks3pl:
        chains_xt = []
        for chain in chains:
            qfxs = [qf_isog_cycle_power(chain[-1],lk)[i] for i in [1,-1]]
            chains_xt+=[chain+[qfx] for qfx in qfxs]
        chains = chains_xt
    return chains

def qf_diag_cands(d,lcands,lks):
    cycdata = qf_cyc_data_ext(d,lcands)
    ls_rem = [lk for lk in cycdata if lk not in lks]
    qf0 = class_group_id(d)
    cands = []
    for lk in ls_rem:
        cyc = qf_isog_cycle_power(qf0,lk)
        cands+=[cyc[1],cyc[-1]]
    return list(set(cands))

def qf_lset_or_chains(d,lks,lcands):
    diag_cands = qf_diag_cands(d,lcands,lks)
    chains = qf_lk_chains(d,lks)
    return [chain for chain in chains if chain[-1] in diag_cands]

def qf_l_gen_search(d,lcands,md=None):
    cld = clgr_size_gen(d)
    if abs(d)<13 or cld==1:
        return {'ls':(),'Success':True,'Type':0,'needs_orientation':False}
    cycdata = qf_cyc_data_ext(d,lcands)
    if md == None:
        md = len(cycdata)
    if cld in cycdata.values():
        lgs = [lk for lk in cycdata if cycdata[lk]==cld]
        lgs.sort(key = lambda lk:lk[0])
        return {'ls':(lgs[0],),'Success':True,'Type':1,'needs_orientation':False}
    # We don't have a cyclic group, so we will need multiple generators
    # Before looking for a generating set we determine whether we will also
    # need an orientation
    need_or = needs_orientation(d,cycdata)
    lks_scores = {(lk,):cycdata[lk] for lk in cycdata}
    for i in range(max(md,len(lcands))):
        newdata = {}
        for lks in lks_scores:
            ls = [lk[0] for lk in lks]
            for lk1 in cycdata:
                lks1_score = (lks_scores[lks]*cycdata[lk1])
                if lk1[0] > max(ls) and cld % lks1_score==0:
                    lks1_l = list(lks)+[lk1]
                    actual_score = len(set(generate_qfs_from_lks(class_group_id(d),lks1_l)))
                    if lks1_score == actual_score:
                        newdata[tuple(lks1_l)]=lks1_score
                        if lks1_score == cld:
                            # We have a generating set! 
                            # Now just check orientation
                            if not need_or:
                                return {'ls':tuple(lks1_l),'Success':True,'Type':2,'needs_orientation':False}
                            chains = qf_lk_chains(d,lks1_l)
                            if len(chains)>0:
                                return {'ls':tuple(lks1_l),'Success':True,'Type':3,'needs_orientation':True,'Chain':chains[0]}
                            # Can either let algorithm continue to run or pass to a simplified algorithm -
                            # we now know that we have more than 1 generator of order > 2, and we know size of gen set, etc.
                            else:
                                return {'ls':tuple(lks1_l),'Success':False,'Type':3,'needs_orientation':True,'Chain':None}
        if len(newdata)>0:
            lks_scores = newdata
        else:
            ms = max(lks_scores.values())
            lks_mx = [lk for lk in lks_scores if lks_scores[lk]==ms]
            return {'ls':tuple(lks_mx[0]),'Success':False,'Type':3,'needs_orientation':need_or}
    ms = max(lks_scores.values())
    lks_mx = [lk for lk in lks_scores if lks_scores[lk]==ms]
    return {'ls':tuple(lks_mx[0]),'Success':False,'Type':4,'needs_orientation':need_or}



# Slow old version that will be replaced by new qf_search_l_gens after testing
def subs_w_prod(lscores:dict,target:int):
    incomp = {():1}
    complete = []
    for l in lscores:
        newdata = {}
        for lt in incomp:
            ltx = tuple(list(lt)+[l])
            n_ltx= lscores[l]*incomp[lt]
            if n_ltx == target:
                complete.append(ltx)
            elif n_ltx<target:
                newdata[ltx] = n_ltx
        incomp.update(newdata)
    return complete

def old_qf_search_lgens(d,lcands):
    cycdata = qf_cyc_data_ext(d,lcands)
    cld = clgr_size_gen(d)
    if cld in cycdata.values():
        return [(l,) for l in cycdata if cycdata[l]==cld]
    ltups_all = subs_w_prod(cycdata,cld)
    # Get rid of combinations that involve the same prime multiple times
    ltups_all= [lks for lks in ltups_all if len(lks)==len(set([lk[0] for lk in lks]))]
    ltups_all.sort(key = len)
    lks_gen = [lk for lk in ltups_all if len(set(generate_qfs_from_lks(class_group_id(d),lk)))==cld]
    if len(lks_gen)==0:
        return []
    ml = min([len(lks) for lks in lks_gen])
    return [lks for lks in lks_gen if len(lks) == ml]